name: acer
services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest            # https://github.com/linuxserver/docker-dokuwiki
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=europe/moscow
    volumes:
      - /vlm_docker/dokuwiki/config:/config
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - 8081:80
    networks:
      mynet:
        ipv4_address: 172.24.0.14
    restart: unless-stopped

networks:
  mynet:
    name: mynet
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-docker24
    ipam:
      config:
      - subnet: 172.24.0.0/24
        gateway: 172.24.0.1